var cipherText = "JBDYZCLNHSIAORDOSSMUMBVRBPCEZSRRTAPFBHYESURVFAVSPAVAEJZCFHYAUWMECSVNUIINJBXOWSIIOAPMJBUEWSISJBTEXVVNFJVRZCLFFSCLJYVCSWKIDWQIOURNZCEEISKOMRDEKIJTSSDENPVRUVRTBZCTISGEPDCEJBKHJGNOSZUHBJVNUVRDUVVAEJRNUOXETHYAUMFUWSYAEVVDJRETTOPAOMDOSSSUUKVVFOCWBMJBFSEUOIJUBZCYDCDMVBZCBHZVFWEASSJESJVDXOPAORZUORVRTHFOEHYAUVVMFOETBUIEBHUEBZDOSSKHBBKHBHZNDCESFELEOQVINWECMWEEEHFRFGVRWSRLMXLDHAVNUGRHBPZTUVRTIOJOQSEEEIGMBBPCVFZOVGEAUIIETHFMFOEDBZJONOUENSKHFJZCUWDOGBFTBTVWWSKESOEBPFVSUVVACBFRNOCMJBUITELIDYKOESKEDHRNEOKTBQYIUGVLGHFTIWJQVOCIUMNHFBZTBDGEBFJIOOEOSARLQSISPBRNEGFIUQRMFOSOVHKHBHZNDCCLFUVIXOJUOXLSUZPADQLSFRFFCSZNHOGOMWKIDWRNCSTAVGVIXOJPSWMYUCKHFGVCSSKGSWVFTCWWJZUUOYEOXBDEOAFSUCWTISTOOTZDFBTETKVRFIESPIXHUTIERIVNUZPIIOMEGSZGOSUSMSVPQFVODQLPBHZOOCIAICJTJZVLFJZTZKYEOWIEBZZZFRSYTCDEVBDITHRKBPCETWXNUVRTBBZNUWDAUSIEWSCAUWFNXOJQVWMESWEGPBKHFVFRJNFNGCITISZNUWDAUSIEWSCAUWFNTCWYPIEGNSEOSOKLFOJTUVVTFFDSJBNHJQYTISPEYDIETGKHFARRFIJUBZCYQZRGJOIITHZCBBUMBFIEEPPOCJZOVGJUQDIETGZOOGIETSIVJBXJVRXMFBKSJGRMBHKESCWIOTZNJHVHPDVIBAJTJZCAMWKTMSRFSOZDPTDITGZNHGFMFHYIOUZFJTFRHSKTIOKATAPFBHYESGEOCPZSIZPSVUXETHVDBBUITBFBCWJHMMIEQSRTBGVNTSFFUVVFVBUANSETBZUEDSECJSJITDRRDSCLFRFUUIEERIRLMMRTCWITI";
var cipherArray = Array.from(cipherText);

/*
1. get first three letters
2. use find(

*/

var substring, re, count;
for(var i = 0; i < cipherText.length -3; i++){
  substring = cipherText.substring(i, i+3);
  re = new RegExp(substring, 'g');
	count = (cipherText.match(re) || []).length;
	console.log(substring + "(" + count + ")");
}
	
//var count = (cipherText.match(/JBD/g) || []).length;

var copy = ciphertext.slice();
copy.unshift("#");
var result = Array();

ciphertext.forEach(count_coincidents);

function count_coincidents(item, index){
	copy.unshift("#");
	var found_coincidents = ciphertext.filter((element, i) => element == copy[i]).length;
	console.log("[" + index + "]" + item + ":" + found_coincidents + ";");
	result.push([index, found_coincidents]);
}
console.log(result);